### PR TITLE
Update the Play JSON dependency

### PR DESCRIPTION
**Pull request by cchantep**

### CODE REVIEW

**Comment by cchantep** [comment]
@wsargent I would say that some methods in the API can be refactored from `JsonNode` to `JsValue` (to decouple the WS API from implementation details of Play JSON).

**Comment by wsargent** [comment]
Thank you!

**Comment by gmethvin** [comment]
@wsargent @cchantep For the Java API, which uses Jackson directly, I would have preferred we just have an `ObjectMapper` as an injected constructor parameter. As written, you have to call `setObjectMapper` somewhere for it to work properly.

**Comment by gmethvin** [comment]
See what I'm working on in playframework/playframework#6969.

**Pull request merged**
