### PR TITLE
Adding methods to retrieve current HTTP method+cookies in Java API

### LINKED ISSUE #231: play.libs.ws.StandaloneWSRequest lacks getMethod
The Scala version has it:

https://github.com/playframework/play-ws/blob/master/play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala#L43

but there is no Java version, only a `setMethod`:

https://github.com/playframework/play-ws/blob/master/play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java#L144

### PR DESCRIPTION
**Pull request by AlejandroRivera**
# Pull Request Checklist

* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Typesafe CLA](https://www.typesafe.com/contribute/cla)?
* [x] Have you [squashed your commits](https://www.playframework.com/documentation/latest/WorkingWithGit#Squashing-commits)?
* [ ] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

## Fixes

Fixes #231 and #232 

## Purpose

Adds new methods to the Java API for the StandaloneWSRequest to retrieve the request method and cookies

### CODE REVIEW

**Comment by AlejandroRivera** [comment]
FYI, the CI build fails with:

```
[info] play-ws-standalone: found 2 potential binary incompatibilities while checking against com.typesafe.play:play-ws-standalone_2.12:1.0.0  (filtered 2)
[error]  * abstract method getCookies()java.util.List in interface play.libs.ws.StandaloneWSRequest is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("play.libs.ws.StandaloneWSRequest.getCookies")
[error]  * abstract method getMethod()java.lang.String in interface play.libs.ws.StandaloneWSRequest is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("play.libs.ws.StandaloneWSRequest.getMethod")
```

Is there something that can be done about this?

**Comment by AlejandroRivera** [comment]
FYI, the CI build broke because:
```
[error]  * abstract method getCookies()java.util.List in interface play.libs.ws.StandaloneWSRequest is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("play.libs.ws.StandaloneWSRequest.getCookies")
[error]  * abstract method getMethod()java.lang.String in interface play.libs.ws.StandaloneWSRequest is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("play.libs.ws.StandaloneWSRequest.getMethod")
```

Since these are new methods in the API, i assume it's safe to ignore those errors?

**Comment by gmethvin** [comment]
> Since these are new methods in the API, i assume it's safe to ignore those errors?

Adding methods to interfaces is a backwards-incompatible change because any code that depends on this library and uses the `StandaloneWSRequest` interface now has to implement the new methods.

One thing we could do is define a default method and throw an `UnsupportedOperationException`. That's not quite so nice but would allow us to break things in a technically binary compatible way. We would need to document the method for now as being *optional* to implement by third party impls, then we can make the final breaking change on master (since 2.x.x can have breaking changes).

wdyt @marcospereira?

Also is there a reason why this was submitted to 1.x.x rather than master? It might be easier to design the right API on master first and then figure out what we need to do for compatibility to backport that change.

**Comment by AlejandroRivera** [comment]
> Adding methods to interfaces is a backwards-incompatible change because any code that depends on this library and uses the `StandaloneWSRequest` interface now has to implement the new methods.

You're right. I assumed the `StandaloneWSRequest` was more of an internal API whose supported implementations were controlled by this project and there was no reasonable risk of breaking other people's code. I'll add the `default` implementation throwing the `UnsupportedOperationException`.

> Also is there a reason why this was submitted to 1.x.x rather than master? It might be easier to design the right API on master first and then figure out what we need to do for compatibility to backport that change.

I had originally made the change on top of `master` branch but i got confused when i saw that in master the version was `1.0.1-SNAPSHOT` and i expected to see `1.1.4-SNAPSHOT`. I then searched where the version `1.1.3` was created/tagged and i found the `1.X.X` branch. I assumed that was the place to introduce the change to have this be released as part of the `1.1.4` version. (I did try to search for any documents/guidelines on the development model to follow, but i failed at that). 

Anyway, based on this comment, i'll "migrate" the code changes to the `master` branch.

**Comment by AlejandroRivera** [comment]
I'm done performing changes (default implementation + PR base). Awaiting for further comments.

**Comment by marcospereira** [comment]
Closing and reopening to Travis build it again.

**Comment by AlejandroRivera** [comment]
@marcospereira anything else i can do to see this PR progress (either to get it merged or get it closed)?

**Comment by marcospereira** [comment]
Hi @AlejandroRivera,

First of all, sorry for the long time to give you a proper answer.

As @gmethvin said before, when submitting pull requests to the master branch, you can break binary compatibility without a problem. We usually try to have a balance between breaking the API and offer a smooth migration path for users, but you can break binary compatibility. When doing so, add the MiMa filters so that we can better track where the API is changing.

Given that, you don't need to provide the default implementation throwing `UnsupportedOperationException` but instead, provide a proper implementation. When backporting this change to 1.x.x branch, then we avoid breaking binary compatibility, and you can open a new PR to add the default implementation throwing `UnsupportedOperationException`.

Thank you and again, sorry for the long time to reply.

**Comment by marcospereira** [comment]
I'm merging this and we can later change the defaults to not throw `UnsupportedOperationException`.

**Pull request merged**
