### PR TITLE
[2.0.x]: Configure binary compatibility check

### PR DESCRIPTION
**Pull request by marcospereira**
## Purpose

Configure binary compatibility check against version 2.0.0.

### CODE REVIEW

**Comment by marcospereira** [comment]
We can later forward port this to master if we want to maintain a list of what is breaking there.

**Comment by dwijnand** [comment]
Looks like a flaky test failed.  Restarted.

**Comment by marcospereira** [comment]
@dwijnand this is now green.

**Comment by dwijnand** [comment]
Forward ported to master: 29c28cb

**Pull request merged**
