### PR TITLE
add new AHC parameter: connectionPoolCleanerPeriod

### PR DESCRIPTION
**Pull request by maxcellent**
# Pull Request Checklist

* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you signed the [Typesafe CLA](https://www.typesafe.com/contribute/cla)?
* [x] Have you [squashed your commits](https://www.playframework.com/documentation/latest/WorkingWithGit#Squashing-commits)?
* [x] Have you added copyright headers to new files?
* [x] Have you checked that both Scala and Java APIs are updated?
* [x] Have you updated the documentation for both Scala and Java sections?
* [x] Have you added tests for any changed functionality?

## Purpose

add new AHC parameter: connectionPoolCleanerPeriod

## Background Context

Sometimes we need to populate idleConnectionInPoolTimeout together with connectionPoolCleanerPeriod

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by maxcellent** [comment]
looks like the build has failed due to some transient issue. But I don't seem to have permission to retry. Can anyone advise what's the next step?

**Comment by renatocaval** [comment]
Hi @maxcellent, 

Thanks for the addition. 

This PR is introducing a binany incompatible change. That's ok, but unfortunately, the build didn't pick that for you. Basically, MiMa was not configuered correctly. 

MiMA is now fixed on the `master` branch. Could you rebase your branch and update the PR? After doing that you may want to run `sbt mimaReportBinaryIssues` and add the exclusions it will report. 

Let us know if you need assistance on that.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by maxcellent** [comment]
hi @renatocaval , I have added MIMA exclusion list and everything seem working fine locally.  However it doesn't seem trigger a new build when I push it again. I can see there is a typesafe cla validation error? but I have already signed the agreement. 

Max

**Comment by renatocaval** [comment]
I can see that you signed it, but the commits here are not associated with the user that signed the CLA. Please, check this link to learn how to fix it. 

https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

I will have a look on the build.

**Comment by renatocaval** [comment]
@maxcellent, build is now green. I will be able to merge this once the CLA issue is sorted out. 

Thanks!

**Comment by maxcellent** [comment]
hi Renato,

Thanks for the reply. However, following this instruction I cannot find a
question mark next to my name as what's showing on the sample page.

https://github.com/playframework/play-ws/pull/416/commits/cffb83a6722e738e4114b2fd278a0a2695402d4c


Max


[image: image.png]

**Comment by renatocaval** [comment]
Closing and reopening to re-trigger the CLA

**Comment by renatocaval** [comment]
@maxcellent, CLA issue is sorted out. This PR is approved and will be merged when the build finishes and if it's green.

**Comment by maxcellent** [comment]
awesome! thank you very much Renato! Wondering what's the release cycle of
this library? When this will be available?

**Pull request merged**
